apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: chat-depl
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels: 
        app: chat
    spec: 
      containers: 
        - name: chat
          image: sydsfn/chats   
          env: 
           - name: MONGO_URI
             valueFrom: 
               secretKeyRef:
                name: mongo-uri-chordchat
                key: MONGO_URI 
           - name: JWT_KEY
             valueFrom: 
               secretKeyRef:
                name: jwt-secret-chordchat
                key: JWT_KEY 
          
           - name: PORT
             value: '3009'
---
apiVersion: v1 
kind: Service 
metadata:
  name: chat-srv
spec: 
  selector:
    app: chat  
  ports:
  - name: chat    
    protocol: TCP 
    port: 3009
    targetPort: 3009 