apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PATCH"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type, Authorization"
    nginx.ingress.kubernetes.io/cors-allow-credentials: 'true'
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
  - host: www.chordchat.site 
    http:
      paths:
      - path: /api/users/?(.*)
        pathType: Prefix
        backend:
          service:
            name: user-auth-srv
            port:
              number: 3001
      - path: /api/user-service/?(.*)
        pathType: Prefix
        backend:
          service:
            name: user-service-srv
            port:
              number: 3002
      - path: /api/ticket-service/?(.*)
        pathType: Prefix
        backend:
          service:
            name: ticket-srv
            port:
              number: 3005
      - path: /api/ticket-order-service/?(.*)
        pathType: Prefix
        backend:
          service:
            name: ticket-order-srv
            port:
              number: 3007
      - path: /api/market/?(.*)
        pathType: Prefix
        backend:
          service:
            name: market-srv
            port:
              number: 3003
      - path: /api/chat-service/?(.*)
        pathType: Prefix
        backend:
          service:
            name: chat-srv
            port:
              number: 3009
      - path: /api/payment-service/?(.*)
        pathType: Prefix
        backend:
          service:
            name: payment-srv
            port:
              number: 3006
      - path: /api/notification-service/?(.*)
        pathType: Prefix
        backend:
          service:
            name: notification-srv
            port:
              number: 3008
      - path: /api/post-service/?(.*)
        pathType: Prefix
        backend:
          service:
            name: post-srv
            port:
              number: 3004
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: 'false'
    service.beta.kubernetes.io/do-loadbalancer-hostname: 'www.chordchat.site'
  labels:
    helm.sh/chart: ingress-nginx-2.0.3
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: 0.32.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller    
