apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: user-service-depl
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels: 
        app: user-service
    spec: 
      containers: 
        - name: user-service
          image: sydsfn/user-service
          env: 
           - name: MONGO_URI
             valueFrom: 
               secretKeyRef:
                name: mongo-uri-chordchat
                key: MONGO_URI 
           - name: PORT
             value: '3002'
---
apiVersion: v1 
kind: Service 
metadata:
  name: user-service-srv
spec: 
  selector:
    app: user-service 
  ports:
  - name: user-service   
    protocol: TCP 
    port: 3002
    targetPort: 3002