name: deploy-ticket-order 

on:
  push:
    branches:
       - master
    paths: 
       - 'ticket-order-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: cd ticket-order-service && docker build -t sydsfn/ticket-order .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME}} 
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
      - run: docker push sydsfn/ticket-order
      - uses: digitalocean/action-doctl@v2
        with: 
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save chordchat
      - run: kubectl rollout restart deployment ticket-order-depl
          
