name: deploy-user-auth 

on:
  push:
    branches:
       - master
    paths: 
       - 'user-auth-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: cd user-auth-service && docker build -t sydsfn/user-auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME}} 
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
      - run: docker push sydsfn/user-auth
          
